### ISSUE TITLE
No Outputs Set by the Action

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/setup-env-github-action#34]
# 🐛 Summary #

This action lists a number of outputs in the [action.yml](../blob/develop/action.yml) file per [the documentation]( https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
). However, no outputs are actually being set when the action runs.

## To reproduce ##

1. Use this action in a workflow
1. Try to use any output specified in the README/`action.yml`

## Expected behavior ##

The outputs listed in the README/`action.yml` should be available when this action is used in a workflow.

## Any helpful log output or screenshots ##

Using the following workflow job:

```yaml
program_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup program versions
        uses: cisagov/setup-env-github-action@develop
        id: cisagov-versions
      - name: Print environment versions
        run: |
          echo ${PACKER_VERSION}
          echo ${TERRAFORM_VERSION}
          echo ${TERRAFORM_DOCS_VERSION}
      - name: Print action output versions
        run: |
          echo ${{steps.cisagov-versions.outputs.PACKER_VERSION}}
          echo ${{steps.cisagov-versions.outputs.TERRAFORM_VERSION}}
          echo ${{steps.cisagov-versions.outputs.TERRAFORM_DOCS_VERSION}}
      - name: Print any action outputs
        run: echo ${{steps.cisagov.versions.outputs}}
```

the following is the output in the Actions console

```console
Run echo ${PACKER_VERSION}
  echo ${PACKER_VERSION}
  echo ${TERRAFORM_VERSION}
  echo ${TERRAFORM_DOCS_VERSION}
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_DIR: ~/.cache/pip
    PACKER_VERSION: 1.7.3
    TERRAFORM_VERSION: 0.12.31
    TERRAFORM_DOCS_VERSION: v0.14.1
1.7.3
0.12.31
v0.14.1

Run echo 
  echo 
  echo 
  echo 
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_DIR: ~/.cache/pip
    PACKER_VERSION: 1.7.3
    TERRAFORM_VERSION: 0.12.31
    TERRAFORM_DOCS_VERSION: v0.14.1



Run echo 
  echo 
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_DIR: ~/.cache/pip
    PACKER_VERSION: 1.7.3
    TERRAFORM_VERSION: 0.12.31
    TERRAFORM_DOCS_VERSION: v0.14.1

```
